adding klorchid link and modifiying orchid config filis

diff --git a/scripts/php/klorchid/klorchid_boilerplate_set b/scripts/php/klorchid/klorchid_boilerplate_set
--- a/scripts/php/klorchid/klorchid_boilerplate_set
+++ b/scripts/php/klorchid/klorchid_boilerplate_set
@@ -10,11 +10,24 @@ then
 TARGET_PATH=.
 fi
 
-
+TARGET_PATH=$(readlink -f $TARGET_PATH)
+echo ""
+echo ""
+echo "This script will DELETE all files inside:"
+echo ""
+echo "    ${bold}$TARGET_PATH${normal} "
+echo ""
+read -p "Are you sure to continue? [Yy]" -n 1 -r
+echo    # (optional) move to a new line
+if [[ ! $REPLY =~ ^[Yy]$ ]]
+then
+    echo "Aborted!"
+    exit 1
+fi
 
 shopt -s extglob
 
-echo "I am in $(cd -P "$symlinkdir" && pwd)"
+
 echo "Deleting current target path files "
 rm -r -f -v !(".git"|".env"|".gitignore"|.|..)
 echo "$TARGET_PATH files deleted "
